### ISSUE TITLE
Add Typescript Build Step to Control Panel

### ISSUE THREAD

**Issue by ghost** [UrbanConsults/Reach-Web-Service#1]
Typescript files should be compiled as AMD modules and follow the same directory layout as the javascript files.

**Comment by ClickSimply** [comment]
Glue code between the JS runtime and Rust is the hardest part here.

A working example of the glue code is in these two files:
https://github.com/UrbanConsults/Reach-Web-Service/blob/master/cli/ops/rws_server.rs
https://github.com/UrbanConsults/Reach-Web-Service/blob/master/cli/js/ops/rws_server.ts
